# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "8.3.3"

    steps:
      - checkout

      # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: pod install

      # Build the app and run tests
      - run:
          name: Build
          command: xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.2,name=iPhone 6s' -workspace TypeAheadSearch.xcworkspace -scheme "TypeAheadSearch" clean build
